### PR TITLE
Replace bufonly with the more feature-ful bdubs

### PR DESCRIPTION
**Pull request by jbranchaud**

### CODE REVIEW

**Comment by dkarter** [comment]
💯

**Comment by jonallured** [comment]
What do you guys think about an alias for `:BO` to `:BD` with a deprecation warning?

**Comment by dkarter** [comment]
The way I read BO is delete all OTHER buffers, BD (or a least if you type :bd) will delete the current buffer.

**Comment by dkarter** [comment]
After looking more into bdubs I totally see your point @jonallured. if you create a PR I'll merge.

**Pull request merged**
