### PR TITLE
Move OS X-specific config to separate file

### PR DESCRIPTION
**Pull request by jonallured**
This commit fixes my problem on my Digital Ocean server, but (unless I'm mistaken) would clobber mouse support for all non-OS X users. :\

I guess what I'm looking for is a way to test for mouse support so that this tmux config doesn't throw errors on my server - thoughts?

### CODE REVIEW

**Comment by dkarter** [comment]
what error are you seeing? maybe we can find a way to conditionally set those tmux options based on the operating system rather than separating the files.

**Comment by jonallured** [comment]
Here are the errors I'm getting:

```
/home/dev/.tmux.conf:40: usage: bind-key [-cnr] [-t mode-table] key command [arguments]
/home/dev/.tmux.conf:41: usage: bind-key [-cnr] [-t mode-table] key command [arguments]
/home/dev/.tmux.conf:39: ambiguous option: mouse
/home/dev/.tmux.conf:42: unknown key: WheelUpPane
/home/dev/.tmux.conf:43: unknown key: WheelDownPane
```

I guess what I'm trying to say is that strictly checking for OS is probably not great. If you check to see whether the OS is Ubuntu, for example, you'd solve my problem on my server, but then desktop Ubuntu users wouldn't have these mouse options set.

I guess that's better than nothing, but sorta seems like kicking the can down the road. What I was hoping for was a better test - something like mouse support, but I didn't have a lot of success when I was looking for something appropriate.

Does that make sense?

**Comment by jgdavey** [comment]
These errors are coming from tmux < 2.1

They totally revamped the mouse-mode options in 2.1, without backward-compatibility. At the time, I couldn't even been able to figure out how to do feature detection.

**Comment by jonallured** [comment]
@jgdavey ugh, that's it - I didn't realize I had two different versions. Closing PR!

**Pull request closed without merging**
